stages:
  - test

tests_php_versions:
  stage: test
  image: registry.gitlab.com/thgnet/docker-centos7wre:v2
  variables:
    RUNTIME_TYPE: development
  parallel:
    matrix:
      - RUNTIME_VERSION: php53
      - RUNTIME_VERSION: php56
      - RUNTIME_VERSION: php72
      - RUNTIME_VERSION: php74
      - RUNTIME_VERSION: php80
      - RUNTIME_VERSION: php81
      - RUNTIME_VERSION: php82
  script:
   - ./bin/fixup_source_files.php check
   - cd tests; ./run_test_case.php cases-basic
